### ISSUE TITLE
dark correction doesn't work properly

### ISSUE THREAD

**Issue by chiahaoliu** [chiahaoliu/xpdAcquireFuncs#10]
Corrected image is incorrect. Need to review the code and see where does it went wrong

**Comment by chiahaoliu** [comment]
Possibly due to over-corrected, i.e. light scan time =0.2 s while dark count time unit = 0.5 s

**Comment by sbillinge** [comment]
try multiplying the dark by 2/5 before subtracting...does it fix the
problem?

On Fri, Oct 23, 2015 at 5:14 PM, chiahaoliu notifications@github.com
wrote:

> Possibly due to over-corrected, i.e. light scan time =0.2 s while dark
> count time unit = 0.5 s
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiahaoliu/xpdAcquireFuncs/issues/10#issuecomment-150694217
> .

## 

---

Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
That could work but might potentially introduce unwanted error to dark image data.
I am thinking to shorten dark scan exposure time to 0.2 s which is the lower limit of pe1 ,so that each dark image can be precisely used as a 'unit'. Also from I see from dark image data, electronic noise goes very small after first few frames, we could / might collect shorter time

**Comment by chiahaoliu** [comment]
Closed. Reproduce QXRD behavior
