### ISSUE TITLE
Store various metadata dictionaries so that search is more powerful

### ISSUE THREAD

**Issue by chiahaoliu** [chiahaoliu/xpdAcquireFuncs#20]
Try to build up a 'data base' of metadata dictionaries.
Save a rich template at somewhere as the first 'data' and also add gs.RE.md from different user/beamtime to enrich 'data base', if this gs.RE.md is largely different from existing ones in database

**Comment by sbillinge** [comment]
on further thought, we could probably just use pickle to write out the list
of dictionary keys, it should be really easy.

S

On Wed, Oct 28, 2015 at 2:32 AM, chiahaoliu notifications@github.com
wrote:

> Try to build up a 'data base' of metadata dictionaries.
> Save a rich template at somewhere as the first 'data' and also add
> gs.RE.md from different user/beamtime to enrich 'data base', if this
> gs.RE.md is largely different from existing ones in database
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiahaoliu/xpdAcquireFuncs/issues/20.

## 

---

Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
as recommended by Tom, will use json to write object. It has better cross-platform compatibility
