### ISSUE TITLE
dark correction method needs to be robust

### ISSUE THREAD

**Issue by chiahaoliu** [chiahaoliu/xpdAcquireFuncs#24]
For now, dark substraction in save_tif() function only works perfectly when exposure time of light images is equal to exposure time of dark images. Possible issue might come from 

> > > > ratio = int(scan_cnt_time /  dark_cnt_time)
> > > > correct_img = light_img - dark_imag*ratio

Need more tests to figure out what reason.

**Comment by chiahaoliu** [comment]
maybe essientially exposure time of dark frames needs to be the same exposure time of light images, like how QXRD operates. Uneqaul exposure time between dark/light frames always leads to over correction, create negative intensities and those negative intensities will be set to 0 in SrXplanar, which results in a flat back ground in I(q)

Real reason for this is unclear yet, electronic signal could be the issue

**Comment by sbillinge** [comment]
I see.  Make sure we get a library of darks with all different exposure
times in that case.....

Good detective work!

On Tue, Nov 10, 2015 at 5:54 AM, Timothy Liu notifications@github.com
wrote:

> maybe essientially exposure time of dark frames needs to be the same
> exposure time of light images, like how QXRD operates. Uneqaul exposure
> time between dark/light frames always leads to over correction, create
> negative intensities and those negative intensities will be set to 0 in
> SrXplanar, which results in a flat back ground in I(q)
> 
> Real reason for this is unclear yet, electronic signal could be the issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chiahaoliu/xpdAcquireFuncs/issues/24#issuecomment-155388116
> .

## 

---

Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by sbillinge** [comment]
So this is almost certainly due to the instability of the detector electronics.  It means that an exposure of 0.4 seconds is not the same as two exposures of 0.2 seconds.

The proper fix for this I think is to go to continuous acquisition and when bluesky requests an "acquire" it merely saves those frames.
