### ISSUE TITLE
get_dark_images works well

### ISSUE THREAD

**Issue by chiahaoliu** [chiahaoliu/xpdAcquireFuncs#3]
@sbillinge 
Works perfectly as we expect but saving tif takes a lot of time; up to num=80 workstation stops saving tif and quit this process.

Maybe only save the last 10 or 20 dark images locally and use uid to pull out more dark frames if it is needed

**Comment by sbillinge** [comment]
I thought of two solutions to this:
1) don't save them locally.  We will write code to do the dark subtraction and this code could pull the tiffs from the database and only write dark-corrected files in the tif_base location.
2) a workaround is the logarithmic collection that we talked about before.  2x0.5, then 10x1., then 10x 100. etc.

**Comment by chiahaoliu** [comment]
Closed:
Take the first solution but slightly modified - only save a few dark frames locally for interrogation if needed. Dark correction is performed in save_tif() function

Also confirmed that dark image quality reaches a stable point after first few frames.
